name: 'shellcheck'
description: 'Shellcheck for sources'

inputs:
  work_dir:
    description: 'Working directory'
    default: '/github/workspace'
  script:
    description: 'Script'
    default: '/tests.sh'
  args:
    description: 'Arguments'
    required: true

runs:
  using: 'docker'
  image: 'test.Dockerfile'
  args:
    - ${{ inputs.work_dir }}
    - ${{ inputs.script }}
    - ${{ inputs.args }}
  env:
    GH_MODE: 1
