name: 'Reusable workflows #1'

concurrency:
  group: ${{ github.ref }}-reusable
  cancel-in-progress: true

on:
  push:
  workflow_call:

env:
  GITHUB_ACTION_PATH: '/home/runner/work/_actions/antirs/test-docker-action/actions-reusable'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: antirs/test-docker-action@actions-reusable
      - run: |
          ls -al "/home/runner/work/_actions/antirs/test-docker-action/actions-reusable/docker"/entrypoint.sh
  reusable-workflow-job-1:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: antirs/test-docker-action@actions-reusable
      - shell: bash
        run: |
          cat ${{ env.GITHUB_ACTION_PATH }}/files/file.txt
  reusable-workflow-job-2:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: antirs/test-docker-action@actions-reusable
      - env:
          DOCKERFILES_PATH: ${{ env.GITHUB_ACTION_PATH }}/docker
        run: |
          env -i DOCKERFILES_PATH=${{ env.DOCKERFILES_PATH }} \
              envsubst < ${{ env.DOCKERFILES_PATH }}/./Dockerfile \
                       > ${{ env.GITHUB_ACTION_PATH }}/./Dockerfile
      - uses: './../../_actions/antirs/test-docker-action/actions-reusable/.github/actions/docker-action-1'
