name: Test shellcheck

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions: {}

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - '**.sh'
  push:
    paths:
      - '**.sh'

jobs:
  test-shellcheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: antirs/test-docker-action@v1
